# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage
osx_image: xcode7.1

language: objective-c
#before_install:
#- gem install cocoapods --no-rdoc --no-ri --no-document --quiet # Since Travis is not always on latest version
#install:
#- gem install xcpretty --no-rdoc --no-ri --no-document --quiet
script:
- set -o pipefail && xcodebuild test -workspace SFFocusViewLayout.xcworkspace -scheme SFFocusViewLayout -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES | xcpretty -c
- pod lib lint --quick

after_success:
- bash <(curl -s https://codecov.io/bash)
